// Rebuild the storefront after editing categories.js or assets/js/parts/store-*.txt.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const files = ['assets/js/categories.js', 'assets/js/parts/store-01.txt', 'assets/js/parts/store-02.txt', 'assets/js/parts/store-03.txt'];
const source = files.map(file => fs.readFileSync(path.join(root, file), 'utf8')).join('');
const output = `/* Generated by node scripts/build-store.cjs. */\n(()=>{const run=()=>{\n${source}\n};window.DENZ_STORE_READY=Promise.resolve(window.DENZ_DATA_READY).then(()=>document.readyState==='loading'?new Promise(resolve=>document.addEventListener('DOMContentLoaded',resolve,{once:true})):undefined).then(run).catch(error=>{console.error(error);document.body.insertAdjacentHTML('beforeend','<div role="alert" style="padding:16px;background:#7f1d1d;color:white">The store could not load. Please refresh the page.</div>');throw error;});})();\n`;
new (require('node:vm').Script)(output);
fs.writeFileSync(path.join(root, 'assets/js/store.js'), output);
console.log('Built one storefront bundle without synchronous requests or eval.');
